CREATE TABLE COMPANIES (
    ID        BIGINT NOT NULL,
    NAME      STRING100 NOT NULL,
    CITY      STRING100,
    ZIP_CODE  STRING6
);

CREATE TABLE EMPLOYEES (
    ID          BIGINT NOT NULL,
    FIRST_NAME  STRING50 NOT NULL,
    LAST_NAME   STRING50,
    COMPANY_ID  BIGINT
);

ALTER TABLE COMPANIES ADD PRIMARY KEY (ID);
ALTER TABLE EMPLOYEES ADD PRIMARY KEY (ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMPLOYEES_1 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (ID);