/******************************************************************************/
/*           Generated by IBExpert 2025.11.12.1 15.11.2025 20:19:29           */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'F:\Firebird_5_0\senteDb.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/*                                  Domains                                   */
/******************************************************************************/

CREATE DOMAIN STRING100 AS
VARCHAR(100);

CREATE DOMAIN STRING50 AS
VARCHAR(50);

CREATE DOMAIN STRING6 AS
VARCHAR(6);



/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE ADD_COMPANY (
    COMPANY_NAME STRING100 NOT NULL,
    CITY STRING100,
    ZIP_CODE STRING6)
AS
BEGIN
  EXIT;
END^



CREATE PROCEDURE ADD_EMPLOYEE (
    COMPANY_ID SMALLINT NOT NULL,
    FIRST_NAME STRING50 NOT NULL,
    LAST_NAME STRING50 NOT NULL)
AS
BEGIN
  EXIT;
END^





SET TERM ; ^



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE COMPANIES (
    ID        SMALLINT NOT NULL,
    NAME      STRING100 NOT NULL,
    CITY      STRING100,
    ZIP_CODE  STRING6
);

CREATE TABLE EMPLOYEES (
    ID          SMALLINT NOT NULL,
    FIRST_NAME  STRING50 NOT NULL,
    LAST_NAME   STRING50,
    COMPANY_ID  SMALLINT
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE COMPANIES ADD PRIMARY KEY (ID);
ALTER TABLE EMPLOYEES ADD PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMPLOYEES_1 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (ID);


/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE ADD_COMPANY (
    COMPANY_NAME STRING100 NOT NULL,
    CITY STRING100,
    ZIP_CODE STRING6)
AS
begin
  INSERT INTO COMPANIES (NAME, CITY, ZIP_CODE) values (:company_name, :city, :zip_code);
end^


ALTER PROCEDURE ADD_EMPLOYEE (
    COMPANY_ID SMALLINT NOT NULL,
    FIRST_NAME STRING50 NOT NULL,
    LAST_NAME STRING50 NOT NULL)
AS
begin
  INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, COMPANY_ID) values (:first_name, :last_name, :company_id);
end^




SET TERM ; ^

